<?php $base_path = base_path(); $directory = path_to_theme();

function audioclassica_regions() {
  return array(
        'left' => t('left sidebar'),
        'right' => t('right sidebar'),
        'centertop' => t('Above Content'),
        'content' => t('content'),
        'header' => t('header'),
        'footer' => t('footer'),
        'login_key' => t('Login Key'),
        'impressum' => t('Impressum'),
        'haupt_menu' => t('Hauptmenu'),
        'fachartikel_navi_links' => t('Fachartikel Navi links'),
        'fachartikel_navi_rechts' => t('Fachartikel Navi rechts'),
        'sekundaerprodukte_eternalarts' => t('Sekundaerprodukte EternalArts'),
      );
} 

/**
* Change the language links
*/
/*function phptemplate_i18n_link($text, $target, $lang, $query= NULL, $fragment = NULL){
  return _phptemplate_callback('i18n_link', array('text' => $text, 'target' => $target, 'lang' => $lang, 'query' => $query, 'fragment' => $fragment));
}*/


function phptemplate_i18n_link($text, $target, $lang, $query= NULL, $fragment = NULL){
$attributes = ($lang == i18n_get_lang()) ? array('class' => 'active') : NULL;
$output .= l(theme('i18n_language_icon', $lang), $target, $attributes, $query, $fragment, FALSE, TRUE);
return $output;
}

function audioclassica_file($element){
$element['#size'] = 30;
return theme_file($element);
}

function _phptemplate_variables($hook, $vars) {
// Load the node region only if we're not in a teaser view.
  if ($hook == 'node' && !$vars['teaser']) {
    // Load region content assigned via blocks.
    foreach (array('fachartikel_navi_links' , 'fachartikel_navi_rechts', 'sekundaerprodukte_eternalarts') as $region) {
      $vars[$region] = theme('blocks', $region);
    }
  }
   if ($hook == 'page') {

    if(module_exists('javascript_aggregator') && $vars['scripts']) {
      $vars['scripts'] = javascript_aggregator_cache($vars['scripts']);
    }
    if (module_exists('page_title')) {
      $vars['head_title'] = page_title_page_get_title();
    }
 //   if (module_exists('page_title')) {
//  $vars['head_title'] = page_title_page_get_title();
//  echo $vars['head_title'];
//}
    
  }
  return $vars;
}

/*
** Den Pager für den View Audio_Klassiker_deutsch auch oben anzeigen
*/

 function theme_views_view_Audio_Klassiker_deutsch($view, $type, $nodes, $level = NULL, $args = NULL) {
  $num_nodes = count($nodes);

  if ($type == 'page') {
    drupal_set_title(filter_xss_admin(views_get_title($view, 'page')));
    views_set_breadcrumb($view);
  }

  //if ($num_nodes) {
//    $output .= views_get_textarea($view, $type, 'header');
//  }

  if ($type != 'block' && $view->exposed_filter) {
    $output .= views_theme('views_display_filters', $view);
  }
  if ($view->use_pager) {
    $output .= "<div class='pager-oben'>" . theme('pager', '', $view->pager_limit, $view->use_pager - 1) . "</div>";
  } // Dies ist der kleine Hack, der den Pager auch oben anzeigt

  $plugins = _views_get_style_plugins();
  $view_type = ($type == 'block') ? $view->block_type : $view->page_type;
  if ($num_nodes || $plugins[$view_type]['even_empty']) {
    if ($level !== NULL) {
      $output .= "<div class='view-summary ". views_css_safe('view-summary-'. $view->name) ."'>". views_theme($plugins[$view_type]['summary_theme'], $view, $type, $level, $nodes, $args) . '</div>';
    }
    else {
      $output .= "<div class='view-content ". views_css_safe('view-content-'. $view->name) ."'>". views_theme($plugins[$view_type]['theme'], $view, $nodes, $type) . '</div>';
    }
    $output .= views_get_textarea($view, $type, 'footer');

    if ($type == 'block' && $view->block_more && $num_nodes >= $view->nodes_per_block) {
      $output .= theme('views_more', $view->real_url);
    }
  }
  else {
    $output .= views_get_textarea($view, $type, 'empty');
  }

  if ($view->use_pager) {
    $output .= theme('pager', '', $view->pager_limit, $view->use_pager - 1);
  }

  if ($output) {
    $output = "<div class='view ". views_css_safe('view-'. $view->name) ."'>$output</div>\n";
  }
  return $output;
}

/**
 * views template to output a view.
 * This code was generated by the views theming wizard
 * Date: Do, 03/26/2009 - 18:30
 * View: Eternal_Arts_Sekundaer
 *
 * This function goes in your template.php file
 */
function phptemplate_views_view_list_Eternal_Arts_Sekundaer($view, $nodes, $type) {
  $fields = _views_get_fields();

  $taken = array();

  // Set up the fields in nicely named chunks.
  foreach ($view->field as $id => $field) {
    $field_name = $field['field'];
    if (isset($taken[$field_name])) {
      $field_name = $field['queryname'];
    }
    $taken[$field_name] = true;
    $field_names[$id] = $field_name;
  }

  // Set up some variables that won't change.
  $base_vars = array(
    'view' => $view,
    'view_type' => $type,
  );

  foreach ($nodes as $i => $node) {
    $vars = $base_vars;
    $vars['node'] = $node;
    $vars['count'] = $i;
    $vars['stripe'] = $i % 2 ? 'even' : 'odd';
    foreach ($view->field as $id => $field) {
      $name = $field_names[$id];
      $vars[$name] = views_theme_field('views_handle_field', $field['queryname'], $fields, $field, $node, $view);
      if (isset($field['label'])) {
        $vars[$name . '_label'] = $field['label'];
      }
    }
    $items[] = _phptemplate_callback('views-list-Eternal_Arts_Sekundaer', $vars);
  }
  if ($items) {
    return theme('item_list', $items);
  }
}







