<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Do, 03/26/2009 - 18:30
 * View: Eternal_Arts_Sekundaer
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   Eternal_Arts_Sekundaer, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $field_image_cache_fid -- 
 * $field_image_cache_fid_label -- The assigned label for $field_image_cache_fid
 * $field_artikel_hauptbild_fid -- 
 * $field_artikel_hauptbild_fid_label -- The assigned label for $field_artikel_hauptbild_fid
 * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 *
 * This function goes in your views-list-Eternal_Arts_Sekundaer.tpl.php file
 */
 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-Eternal_Arts_Sekundaer.css');
  
  ?>
<div class="sekundaerprodukte-view">

<?php if (isset($node->node_data_field_image_cache_field_image_cache_fid)) : ?>
<div class="view-field view-data-field-image-cache-fid">
  <?php print $field_image_cache_fid ?>
</div>
<?php endif; ?>


<?php if (isset($node->node_data_field_artikel_hauptbild_field_artikel_hauptbild_fid)) : ?>
<div class="view-field view-data-field-artikel-hauptbild-fid">
  <?php print $field_artikel_hauptbild_fid ?>
</div>
<?php endif; ?>

<div class="view-field view-data-title">
  <?php print $title ?>
</div>
<div class="cleardiv"></div>
</div>
